title: CedMod Documentation
description: Documentation for Installation and Usage of CedMod
theme: just-the-docs
color_scheme: dark

url: https://docs.cedmod.nl
baseurl: /

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple